### ISSUE TITLE
Unsported attribute: clean_percent of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.  r

### ISSUE THREAD

**Issue by bruesche** [copystring/ioBroker.roborock#365] opened 2023-09-01 09:51 UTC
Get Error in Log of iobroker:

Unsported attribute: clean_percent of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.
 
Used Adapter version 0.2.1.

Roborock Model S7 maxV.

latest Version of IOBroker Admin and Linux Bullseye..

Can anybody help

**Comment by copystring** [comment] 2023-09-01 10:05
Duplicate of https://github.com/copystring/ioBroker.roborock/issues/348

You need to wait for 0.3.1 to be in stable or use latest repo of iobroker to get 0.3.1 now.

**Closed** 2023-09-01 10:05 UTC
