### ISSUE TITLE
This object will not be created in future versions. Please report this to the developer.

### ISSUE THREAD

**Issue by MichaMican** [copystring/ioBroker.roborock#120] opened 2023-03-26 14:12 UTC
**Describe the bug**  
On first start a warn message appears that states "This object will not be created in future versions. Please report this to the developer."

**To Reproduce**  
1. Install Adapter
2. Sign in
3. Check the logs (see screenshot)

**Expected behavior**  
No warn message

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/45571948/227781373-787da7c7-6b11-46cb-b906-95ec5ea45d82.png)

**Versions:**  
 - Adapter version: v0.1.6
 - JS-Controller version: v4.0.24
 - Node version: v16.19.1
 - Operating system: Raspbian ioBroker

**Additional context**

**Comment by copystring** [comment] 2023-03-26 21:46
Duplicate of https://github.com/copystring/ioBroker.roborock/issues/117

**Closed by copystring** 2023-03-26 21:46 UTC
