### ISSUE TITLE
[BUG] Device not supported - roborock.vacuum.a21

### ISSUE THREAD

**Issue by dobmeierr** [copystring/ioBroker.roborock#726] opened 2024-12-10 10:03 UTC
### Bug Description

The new Roborock Qrevo Slim is not supported by the adapter.

### Steps to Reproduce

try to use the exact device I mantioned here

### Expected Behavior

using the adapter for my new device

### Debug Log

`2024-12-10 10:58:30.605 - error: roborock.0 (136639) Failed to execute null on robot null (roborock.vacuum.a21): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!
--
2024-12-10 10:58:34.651 - error: roborock.0 (136639) Failed to execute null on robot null (roborock.vacuum.a21): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!
2024-12-10 10:58:38.904 - error: roborock.0 (136639) Failed to execute null on robot null (roborock.vacuum.a21): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!
2024-12-10 10:58:52.649 - warn: roborock.0 (136639) Failed to execute get_network_info on robot 6qwAVzLXCRsAhG02FSIYTK (roborock.vacuum.a21): Error: Local request with id 0 with method get_network_info timed out after 10 seconds Local connect state: undefined
2024-12-10 10:58:54.909 - error: roborock.0 (136639) Failed to execute client.on("error") on robot undefined (unknown model): MQTT connection error: Error: connack timeout
2024-12-10 10:58:54.940 - error: roborock.0 (136639) Failed to execute client.on("offline") on robot undefined (unknown model): MQTT connection offline: undefined
2024-12-10 10:58:54.942 - warn: roborock.0 (136639) Restart initiated
2024-12-10 10:58:54.944 - info: roborock.0 (136639) MQTT connection close.
2024-12-10 10:58:54.993 - info: roborock.0 (136639) terminating
2024-12-10 10:58:54.994 - info: roborock.0 (136639) Terminated (NO_ERROR): Without reason
2024-12-10 10:58:55.445 - info: roborock.0 (136639) terminating
2024-12-10 10:58:55.537 - info: host.AW5-23-200198 instance system.adapter.roborock.0 terminated with code 0 (NO_ERROR)
2024-12-10 10:58:55.538 - info: host.AW5-23-200198 Restart adapter system.adapter.roborock.0 because enabled
2024-12-10 10:59:25.785 - info: host.AW5-23-200198 instance system.adapter.roborock.0 in version "0.6.17" started with pid 136684
2024-12-10 10:59:27.694 - info: roborock.0 (136684) starting. Version 0.6.17 in /opt/iobroker/node_modules/iobroker.roborock, node: v20.18.1, js-controller: 7.0.3
2024-12-10 10:59:27.705 - info: roborock.0 (136684) Starting adapter. This might take a few minutes depending on your setup. Please wait.
2024-12-10 10:59:28.315 - info: roborock.0 (136684) MQTT initialized
2024-12-10 10:59:36.180 - error: roborock.0 (136684) Failed to execute null on robot null (roborock.vacuum.a21): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!
2024-12-10 10:59:40.372 - error: roborock.0 (136684) Failed to execute null on robot null (roborock.vacuum.a21): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!
2024-12-10 10:59:44.262 - error: roborock.0 (136684) Failed to execute null on robot null (roborock.vacuum.a21): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!`

### Adapter Version

0.6.17

### JS-Controller Version

7.0.3

### Node.js Version

20.18.1

### Operating System

Debian

**Comment by copystring** [comment] 2024-12-11 22:50
Duplicate of https://github.com/copystring/ioBroker.roborock/issues/719. Fix coming in next release.

**Closed by copystring** 2024-12-11 22:50 UTC
Labels: bug
